name: Amy Gohal
favicon: null
layout_spectrum: 0.7265099084470421
typography_spectrum: 0.9088075258769095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8317411623429507
  lightness: 0.2711465028114617
  saturation: 0.7644453376997262
  rhythmicContrast: 0.8342927468474954
purpose: []
